# Basic
title: W.B
subtitle: Note && Blog
description: 苟利国家生死以，岂因祸福避趋之
#creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
#nav:
#    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    #weibo: 1005051901400391
    github: wangbin11
    #gplus: 107108267983477358170
    mail: wangbinjs@126.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
